name: Run Weaviate on Linux

on:
  push:
    branches:
    - main
    paths:
    - run-weaviate.ipynb
  pull_request:
    branches:
    - main
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Check Hardware Spec
      run: /bin/bash ./scripts/get_hardware_info.sh
    - name: Cache dataset
      uses: actions/cache@v4
      with:
        path: |
          dataset
        key: ${{ runner.os }}-dataset
    - name: Download data
      run: /bin/bash ./scripts/setup.sh gha
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Cache pip modules
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run ANN search
      run: papermill run-weaviate.ipynb output-weaviate-linux.ipynb --log-output
    - name: 'Upload Results'
      uses: actions/upload-artifact@v4
      with:
        name: performance-result
        path: results.json

