name: Run Qdrant on Linux

on:
#  push:
#    branches:
#    - main
  pull_request:
    branches:
    - main
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Check Hardware Spec
      run: /bin/bash ./scripts/get_hardware_info.sh
    - name: Cache dataset
      uses: actions/cache@v4
      with:
        path: |
          dataset
        key: ${{ runner.os }}-dataset
    - name: Download data
      run: /bin/bash ./scripts/download.sh gha
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: 3.10
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run ANN search
      run: papermill run-qdrant.ipynb output-qdrant-linux.ipynb --log-output

